name: python-ci

on: [push, pull_request]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10',
                         '3.11',
                         '3.12',
                         '3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[dev]'
        pip install pytest
        pip install pytest-cov
    - name: Lint code with ruff
      run: | 
        ruff check kinisi/*
    - name: Check code formatting with ruff
      run: |
        ruff format --check kinisi/*
    - name: Generate coverage report
      run: |
        pytest --cov-report xml:coverage.xml --cov=kinisi 
    - name: Get Cover 
      uses: orgoro/coverage@v3.2
      with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
